### ISSUE TITLE
CVO cannot rely on openshift resources

### ISSUE THREAD

**Issue by deads2k** [openshift/cluster-version-operator#23]
The CVO is creating an SCC for itself. This fails when installing on a kube-cluster and since the openshift-apiserver is created via an operator installed by the CVO, this creates a cycle.

Instead, create a clusterrole and clusterrolebinding for the SCC that will eventually exist.

**Comment by abhinavdahiya** [comment]
> Instead, create a clusterrole and clusterrolebinding for the SCC that will eventually exist.

Do you mean create scc for itself?

**Comment by deads2k** [comment]
Currently the SCC is listed in the manifests. This won't work.  The openshift-apiserver bootstraps a `privileged` SCC when it comes up.  You can create the RBAC resources in your manifests instead and avoid the cycle.

**Comment by abhinavdahiya** [comment]
@deads2k I'm sorry I'm not completely sure how SCCs works. 😞

Can you point me some docs that show how?

**Comment by deads2k** [comment]
> @deads2k I'm sorry I'm not completely sure how SCCs works. 
> 
> Can you point me some docs that show how?

@enj Can you link to docs?  I didn't see it here https://docs.okd.io/latest/admin_guide/manage_scc.html

**Comment by enj** [comment]
https://docs.okd.io/latest/architecture/additional_concepts/authorization.html#rbac-to-scc

Join `#forum-auth` if you need further assistance.

**Comment by enj** [comment]
CVO already has https://github.com/openshift/cluster-version-operator/blob/master/install/0000_00_cluster-version-operator_02_roles.yaml so the SCC YAML should just be removed.  It can already do everything, including use any SCC or PSP.
