### ISSUE TITLE
Provide the cluster ID in cluster_version Prometheus metrics

### ISSUE THREAD

**Issue by chambridge** [openshift/cluster-version-operator#342]
Access to the Cluster Version k8s object requires cluster role access, which makes it difficult to obtain the cluster ID.

[Operator-metering](https://github.com/operator-framework/operator-metering) is a useful tool for building reports from Prometheus data. For upcoming flows and customer interactions (support, billing, etc) it would be beneficial for the reports to contain the cluster ID.

If the cluster ID was available as label or its own metric in Prometheus that would help to simplify report origination.

**Comment by smarterclayton** [comment]
This probably belongs to one of the existing metrics like cluster invoker as label `id`.

**Comment by zerodayz** [comment]
I am working on this at the moment, as @smarterclayton suggested, I wouldn't also include this as part of cluster_version, but rather as part of cluster_installer. I ll add it as part of that, we can re-work if we decide otherwise.

**Comment by wking** [comment]
kube-reporting/metering-operator#1457 says metering-operator is no longer being developed.  Do we still have a use-case for exposing the cluster ID via a label?  I'm having a hard time thinking of an in-cluster use-case, and for external metrics, we get `_id` injected automatically by the Telemeter client or some such.

**Comment by chambridge** [comment]
This information would be valuable to operators like the cost operator or Red Hat Marketplace operator. It would allow these operators to potentially reduce the rbac needs on the service accounts for the operator.
