### ISSUE TITLE
Unable to add whitelist annotation to cli downloads route

### ISSUE THREAD

**Issue by stujb** [openshift/cluster-version-operator#651]
We would like to be able to restrict by IP access to the downloads route in the openshift-console project using the ip whitelist annotation. 

This currently does not appear possible as any update to add the required annotation is reverted by the cluster-version-operator

**Comment by wking** [comment]
In openshift/console-operator#508, the console folks removed the `downloads` Deployment manifest asking the CVO to manage this resource, and now they manage that resource directly.  So if you have concerns with their management, probably take that up with them?
