### ISSUE TITLE
Question: how to config the CSV to use the latest version of one operator?

### ISSUE THREAD

**Issue by jianzhangbjz** [openshift/cluster-version-operator#70]
Hi, All

I built a cluster by using the openshif-installer `v0.6.0` today. But, I find the manifest of the OLM is old, so how to use the latest version of the OLM? Details as below:
```console
[jzhang@dhcp-140-18 installer]$  oc get clusterversion version -o yaml
...
    current:
      payload: quay.io/openshift-release-dev/ocp-release@sha256:4f02d5c7183360a519a7c7dbe601f58123c9867cd5721ae503072ae62920575b
      version: 0.0.1-2018-12-08-172651
...
[jzhang@dhcp-140-18 installer]$ oc adm release extract --from=quay.io/openshift-release-dev/ocp-release@sha256:4f02d5c7183360a519a7c7dbe601f58123c9867cd5721ae503072ae62920575b --to=release-payload
[jzhang@dhcp-140-18 installer]$ ls release-payload/ | grep 30
0000_30_00-namespace.yaml
0000_30_01-olm-operator.serviceaccount.yaml
0000_30_02-clusterserviceversion.crd.yaml
0000_30_03-installplan.crd.yaml
0000_30_04-subscription.crd.yaml
0000_30_05-catalogsource.crd.yaml
0000_30_06-rh-operators.configmap.yaml
0000_30_07-certified-operators.configmap.yaml
0000_30_08-certified-operators.catalogsource.yaml
0000_30_09-rh-operators.catalogsource.yaml
0000_30_10-olm-operator.deployment.yaml
0000_30_11-catalog-operator.deployment.yaml
0000_30_12-aggregated.clusterrole.yaml
0000_30_13-packageserver.csv.yaml
0000_30_14-operatorgroup.crd.yaml
```
One more question, if I want to update this CVO to the latest version, how to do that? The current version is `0.0.1-2018-12-08-172651`.

**Comment by jianzhangbjz** [comment]
@wking Could you help answer my questions? I could not find related docs, thanks very much.

**Comment by wking** [comment]
Follow [these docs][1] to take over control of a given object from the CVO.  Once you've told the CVO to leave the object alone, you can update it as you see fit without getting stomped on.

[1]: https://github.com/openshift/cluster-version-operator/blob/master/docs/dev/clusterversion.md#setting-objects-unmanaged

**Comment by jianzhangbjz** [comment]
Thanks for your response! But, I mean how can we update specific object via CVO automatically.
We can set `--enable-auto-update=true` to update all objects, but how to update specific object via CVO automatically? Not all objects.
Yeah, we can stop the CVO, and then update the object manually, only this one approach? And, for this manually way, where can we get the exact image id of the object?

**Comment by jianzhangbjz** [comment]
Thanks! But, how to update payload? I could not find the image id of the latest version of the object.

**Comment by wking** [comment]
> But, how to update payload?

You could use [`oc adm realease new ...`][1].

> I could not find the image id of the latest version of the object.

[Docs][2].

[1]: https://github.com/openshift/origin/blob/master/pkg/oc/cli/admin/release/new.go
[2]: https://github.com/openshift/cluster-version-operator/blob/master/docs/dev/clusterversion.md#finding-your-current-update-payload

**Comment by jianzhangbjz** [comment]
@wking I look through that docs, but, I'm sorry, I still confused about how to update a 2nd operator running in the cluster. 
For example, the `ingress-operator` ran failed, and I was told to update it to the latest version, but how to update it? I don't want to recreate the whole cluster. Could you help give me more details? 
```console
mac:jian jianzhang$ oc get pods -n openshift-ingress-operator
NAME                                READY     STATUS             RESTARTS   AGE
ingress-operator-555494ccc4-m5jmc   0/1       CrashLoopBackOff   558        1d
mac:jian jianzhang$ oc get clusterversion
NAME      VERSION                           AVAILABLE   PROGRESSING   SINCE     STATUS
version   4.0.0-0.alpha-2018-12-21-211512   True        False         1d        Cluster version is 4.0.0-0.alpha-2018-12-21-211512
```

**Comment by jianzhangbjz** [comment]
@wking One more question, what's the `VERSION: 4.0.0-0.alpha-2019-01-01-225811)` means? The cluster created date? If yes, what's the  `225811` means?
```console
mac:aws-ocp jianzhang$ oc get clusterversion
NAME      VERSION                           AVAILABLE   PROGRESSING   SINCE     STATUS
version   4.0.0-0.alpha-2019-01-01-225811   True        False         3h        Cluster version is 4.0.0-0.alpha-2019-01-01-225811
```

**Comment by wking** [comment]
> For example, the `ingress-operator` ran failed, and I was told to update it to the latest version, but how to update it? I don't want to recreate the whole cluster.

Reliably updating a live cluster is still a work in progress.  For now, it's easiest to tear down your old cluster and launch a new one.  Once we have reliable updates, updating the whole cluster (vs. bumping a single component) will be more reliable because it reduces the chances of mismatched components.

> One more question, what's the VERSION: 4.0.0-0.alpha-2019-01-01-225811) means?

That means your cluster is running the update payload with that tag (see [here][1] for recent tags).  225811 means the tag was created at 22:58:11 UTC, although it still has to pass some post-testing before it's accepted as `registry.svc.ci.openshift.org/openshift/origin-release:v4.0`.

And these CI images have a short lifespan anyway before they're garbage-collected.  If you want a long-running cluster, you should be using the images which have been pushed to quay.io.  The [released installers][2] have been set up to use those released images (e.g. via openshift/installer#972).

[1]: https://origin-release.svc.ci.openshift.org/
[2]: https://github.com/openshift/installer/releases

**Comment by jianzhangbjz** [comment]
> Once we have reliable updates, updating the whole cluster (vs. bumping a single component) will be more reliable because it reduces the chances of mismatched components.

Glad to know this, thanks!

> That means your cluster is running the update payload with that tag (see here for recent tags)

Thank you! This is centenly I want to know.

>   If you want a long-running cluster, you should be using the images which have been pushed to quay.io.

Thanks! I create the cluster by using the release v0.8.
```console
mac:payload-v0.8 jianzhang$ oc get clusterversion
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE     STATUS
version   4.0.0-8   True        False         3h        Cluster version is 4.0.0-8
mac:payload-v0.8 jianzhang$ openshift-install version
openshift-install v0.8.0
``` 
Yes, I can see it used the images stored in quay.io. For example:
```console
mac:payload-v0.8 jianzhang$ cat image-references |grep "operator-lifecycle-manager" -A 5
        "name": "operator-lifecycle-manager",
        "annotations": {
          "io.openshift.build.commit.id": "66be86ab7ca1771bc17fa216ed21053803a2307f",
          "io.openshift.build.commit.ref": "master",
          "io.openshift.build.source-location": "https://github.com/operator-framework/operator-lifecycle-manager"
        },
        "from": {
          "kind": "DockerImage",
          "name": "quay.io/openshift-release-dev/ocp-v4.0@sha256:48f4a6500f506fc84d81d73e38178133cd7cfc3349de49c6240eae35dd567cd4"
        },
```
I was wondering where the `quay.io/openshift-release-dev/ocp-v4.0@sha256:48f4a6500f506fc84d81d73e38178133cd7cfc3349de49c6240eae35dd567cd4`image from? Who owns build it? The CI opeartor? If yes, how can I replace it with the downstream image?
