### ISSUE TITLE
Ubi image unavailable to public

### ISSUE THREAD

**Issue by jaitaiwan** [openshift/cluster-version-operator#943]
Hey folks,

As apart of the contributing documentation there's no mention of requiring a login to build the container image. In this case it's the `registry.ci.openshift.org/ocp/ubi` container image that appears to require authentication.

Can you please clarify if there is a authentication method for public contributors or if there should be a different URL there?

**Comment by petr-muller** [comment]
I think this was resolved by https://github.com/openshift/cluster-version-operator/pull/944 ?

**Comment by jaitaiwan** [comment]
Yup I believe that'll do it. Ill reopen if it doesn't. Thanks!
